<div class="row">
    <h1><?=$project['name']?></h1>
    <p>Submitted by <a href="https://github.com/<?=$project['submitter']?>">@<?=$project['submitter']?></a> on <?=$project['submissionDate']?></p>
</div>
<div class="row">
    <div class="col-sm-5">
        <img src="<?=$cdn?>/projects/<?=$project['permalink']?>/thumb.png" width="470">
    </div>
    <div class="col-sm-7">
        <table class="table table-condensed table-striped table-bordered">
            <tbody>
                <?php if (isset($project['name'])): ?>
                <tr>
                    <th class="col-sm-3">Name</th>
                    <td><?=$project['name']?></td>
                </tr>
                <?php endif; ?>
                <?php if (isset($project['url'])): ?>
                <tr>
                    <th class="col-sm-3">Url</th>
                    <td>
                        <a href="<?=$project['url']?>" target="_blank">
                            <?=$project['url']?>
                        </a>
                    </td>
                </tr>
                <?php endif; ?>
                <?php if (isset($project['info'])): ?>
                <tr>
                    <th class="col-sm-3">Info</th>
                    <td>
                        <a href="<?=$project['info']?>" target="_blank">
                            <?=$project['info']?>
                        </a>
                    </td>
                </tr>
                <?php endif; ?>
                <?php if (isset($project['src'])): ?>
                <tr>
                    <th class="col-sm-3">Source</th>
                    <td>
                        <a href="<?=$project['src']?>" target="_blank">
                            <?=$project['src']?>
                        </a>
                    </td>
                </tr>
                <?php endif; ?>
                <?php if (isset($project['tags'])): ?>
                <tr>
                    <th class="col-sm-3">Tags</th>
                    <td class="col-sm-9">
                        <?php foreach ($project['tags'] as $tag): ?>
                            <span class="label label-primary"><?=$tag?></span>
                        <?php endforeach; ?>
                    </td>
                </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-sm-12">
        <p><strong><?=$project['summary']?></strong></p>
        <p><?=nl2br($project['description'])?></p>
    </div>
</div>
<hr />

<?php if (isset($project['images']) && !empty($project['images'])): ?>
<div class="row">
    <div class="col-sm-12 lightbox-image">
        <?php foreach ($project['images'] as $image): ?>
        <div class="col-sm-4">
            <a href="<?=$cdn?>/projects/<?=$project['permalink']?>/<?=$image["name"]?>" data-toggle="lightbox" data-gallery="multiimages" data-title="<?=$image["description"]?>" class="thumbnail">
                <img src="<?=$cdn?>/projects/<?=$project['permalink']?>/<?=$image["name"]?>" class="img-responsive">
            </a>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
