<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Built with Phalcon</title>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <?php echo $this->tag->stylesheetLink("css/ekko-lightbox.css") ?>
        <?php echo $this->tag->stylesheetLink("css/builtwith.css") ?>
        <link href="http://static.phalconphp.com/favicon.ico" rel="icon" type="image/ico" />
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            body { margin-top: 60px; }
        </style>
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a href="http://phalconphp.com/en/" class="navbar-brand">
                        <img src="http://static.phalconphp.com/images/logo.png" alt="logo" class="logo">
                        <?php echo $this->tag->image(array("img/logo-text.png", "alt" => "logo", "class" => "logo-text")) ?>
                    </a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="/">
                        <b class="glyphicon glyphicon-home"></b> Home
                    </a></li>
                    <li><a href="https://github.com/phalcon/builtwith#submit">
                        <b class="glyphicon glyphicon-bookmark"></b> Submit Project
                    </a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            <?=$this->getContent()?>
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//rawgithub.com/ashleydw/lightbox/master/dist/ekko-lightbox.js"></script>
        <script type="text/javascript">
            $(document).ready(function ($) {

                // delegate calls to data-toggle="lightbox"
                $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
                    event.preventDefault();
                    return $(this).ekkoLightbox({
                        onShown: function() {
                            if (window.console) {
                                return console.log('Checking our the events huh?');
                            }
                        }
                    });
                });

                //Programatically call
                $('#open-image').click(function (e) {
                    e.preventDefault();
                    $(this).ekkoLightbox();
                });
                $('#open-youtube').click(function (e) {
                    e.preventDefault();
                    $(this).ekkoLightbox();
                });
            });
        </script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function() {
                $('input[type=checkbox], input[type=radio], select').on('click', function() {
                    var parent = this.parentNode;

                    if (!($(this).is(':checked'))) {
                        $(parent).removeClass('label-success').addClass('label-danger');
                    } else {
                        $(parent).removeClass('label-danger').addClass('label-success');
                    }

                    tags    = $('input[type=checkbox]:checked').serialize();
                    page    = $('input[name=page]:checked').val();
                    counter = $('select option:selected').text();

                    if ( tags ) {
                        url = tags + '&page=' + page + '&counter=' + counter;
                    } else {
                        url = 'page=' + page + '&counter=' + counter;
                    }

                    $.post('/filter', url, function(data) {
                        $('#product-list').html(data);
                    });
                });
            });
        </script>
    </body>
</html>
