<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Built with Phalcon</title>

        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <?php echo $this->tag->stylesheetLink("{$cdn}/css/ekko-lightbox.css", false) ?>
        <?php echo $this->tag->stylesheetLink("{$cdn}/css/builtwith.css", false) ?>
        <link href="https://static.phalconphp.com/www/favicon.ico" rel="icon" type="image/ico" />
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            body { margin-top: 60px; }
        </style>
    </head>

    <body>
        <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="https://phalconphp.com/en/" class="navbar-brand">
                        <img src="https://static.phalconphp.com/www/images/logo.png" alt="logo" class="logo">
                        <?php echo $this->tag->image(array("{$cdn}/img/logo-text.png", "alt" => "logo", "class" => "logo-text"), false) ?>
                    </a>
                </div>
                <div class="navbar-collapse collapse" style="height: 1px;">
                    <ul class="nav navbar-nav">
                        <li><a href="/"><b class="glyphicon glyphicon-home"></b> Home</a></li>
                        <li><a href="https://github.com/phalcon/builtwith#submit"><b class="glyphicon glyphicon-bookmark"></b> Submit Project</a></li>
                    </ul>
                </div><!-- /.nav-collapse -->
            </div><!-- /.container -->
        </div>

        <div class="container content">
            <?=$this->getContent()?>
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script type="application/javascript" src="https://cdn.rawgit.com/ashleydw/lightbox/master/dist/ekko-lightbox.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function ($) {

                // delegate calls to data-toggle="lightbox"
                $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
                    event.preventDefault();
                    return $(this).ekkoLightbox({
                        onShown: function() {
                            if (window.console) {
                                return console.log('Checking our the events huh?');
                            }
                        }
                    });
                });

                //Programatically call
                $('#open-image').click(function (e) {
                    e.preventDefault();
                    $(this).ekkoLightbox();
                });
                $('#open-youtube').click(function (e) {
                    e.preventDefault();
                    $(this).ekkoLightbox();
                });
            });
        </script>
        <script>
            $(document).ready(function() {
                $('input[type=checkbox], input[type=radio], select').on('click', function() {
                    var parent = this.parentNode;

                    $('.loading-container').show();
                    $('.project-container').hide();

                    if (!($(this).is(':checked'))) {
                        $(parent).removeClass('label-success').addClass('label-danger');
                    } else {
                        $(parent).removeClass('label-danger').addClass('label-success');
                    }

                    tags    = $('input[type=checkbox]:checked').serialize();
                    page    = $('input[name=page]:checked').val();
                    counter = $('select option:selected').text();

                    if ( tags ) {
                        url = tags + '&page=' + page + '&counter=' + counter;
                    } else {
                        url = 'page=' + page + '&counter=' + counter;
                    }

                    $.post('/filter', url, function(data) {
                        $('#product-list').html(data);

                        var content = $('.content');

                        $(content[1]).css('padding', 0);

                        $('.loading-container').hide();
                        $('.project-container').show();
                    });
                });

                $('.paginate-count').on('change', function() {
                    counter = $('select option:selected').text();
                    url = tags + '&page=' + page + '&counter=' + counter;

                    $.post('/filter', url, function(data) {
                        $('#product-list').html(data);

                        var content = $('.content');

                        $(content[1]).css('padding', 0);

                        $('.loading-container').hide();
                        $('.project-container').show();
                    });
                })
            });
        </script>
    </body>
</html>
