<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Built with PhalconPHP</title>

        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            body { margin-top: 60px; }
        </style>
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand">PhalconPHP</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="/">
                        <b class="glyphicon glyphicon-home"></b> Home
                    </a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            <?=$this->getContent()?>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function() {
                $('input[type=checkbox]').on('click', function() {
                    var parent = this.parentNode;
                    if (!($(this).is(':checked'))) {
                        $(parent).removeClass('label-success').addClass('label-danger');
                    } else {
                        $(parent).removeClass('label-danger').addClass('label-success');
                    }
                    $.post('/filter', $(parent.parentNode).serialize(), function(data) {
                        $('#product-list').html(data);
                    });
                });
            });
        </script>
    </body>
</html>
